services:
    Github\Client:
        factory: 'Nyholm\GitReviewer\Service\GithubFactory::create'
        arguments: ['@Github\HttpClient\Builder', '%env(default::GITHUB_TOKEN)%']

    Github\HttpClient\Builder:
        arguments:
            - '@github.httplug_client'
            - '@Psr\Http\Message\ResponseFactoryInterface'
            - '@Psr\Http\Message\StreamFactoryInterface'

    github.httplug_client:
        class: Symfony\Component\HttpClient\Psr18Client
        arguments:
            - '@http_client'
            - '@Psr\Http\Message\ResponseFactoryInterface'
            - '@Psr\Http\Message\StreamFactoryInterface'
